-- Seed data for trainings (Multilingual JSON)
INSERT INTO public.trainings (id, title, description, type, start_date, end_date, trainer, capacity, location, status, image_url)
VALUES 
    ('e1b1a1a1-1111-4111-a111-111111111111', 
     '{"fr": "Introduction à la Cybersécurité pour les Administrateurs", "en": "Introduction to Cybersecurity for Administrators"}', 
     '{"fr": "Une formation complète sur les bases de la sécurité informatique, la gestion des risques et les meilleures pratiques pour protéger les infrastructures critiques.", "en": "A comprehensive training on the basics of IT security, risk management and best practices for protecting critical infrastructure."}', 
     'online', 
     NOW() + INTERVAL '7 days', 
     NOW() + INTERVAL '14 days', 
     'Dr. Amadou Diallo', 
     100, 
     NULL, 
     'published', 
     'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&auto=format&fit=crop&q=60'),
    
    ('e2b2a2a2-2222-4222-a222-222222222222', 
     '{"fr": "Gestion de Projet Agile & Scrum", "en": "Agile & Scrum Project Management"}', 
     '{"fr": "Apprenez à gérer vos projets de transformation numérique avec les méthodologies Agiles. Focus sur le rôle de Scrum Master et Product Owner.", "en": "Learn to manage your digital transformation projects with Agile methodologies. Focus on the role of Scrum Master and Product Owner."}', 
     'onsite', 
     NOW() + INTERVAL '15 days', 
     NOW() + INTERVAL '20 days', 
     'Mme Sarah Kouamé', 
     25, 
     'Abidjan, Côte d''Ivoire', 
     'published', 
     'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=800&auto=format&fit=crop&q=60'),

    ('e3b3a3a3-3333-4333-a333-333333333333', 
     '{"fr": "Transformation Numérique des Services Publics", "en": "Digital Transformation of Public Services"}', 
     '{"fr": "Comprendre les enjeux de la dématérialisation et de l''e-gouvernance pour améliorer le service aux citoyens.", "en": "Understand the challenges of dematerialization and e-governance to improve service to citizens."}', 
     'online', 
     NOW() - INTERVAL '2 days', 
     NOW() + INTERVAL '5 days', 
     'M. Jean-Pierre Mbengue', 
     200, 
     NULL, 
     'published', 
     'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop&q=60'),

    ('e4b4a4a4-4444-4444-a444-444444444444', 
     '{"fr": "Maintenance des Infrastructures Fibre Optique", "en": "Fiber Optic Infrastructure Maintenance"}', 
     '{"fr": "Formation technique sur la soudure, le test et la maintenance curative des réseaux de transport et de distribution.", "en": "Technical training on welding, testing and curative maintenance of transport and distribution networks."}', 
     'onsite', 
     NOW() + INTERVAL '30 days', 
     NOW() + INTERVAL '35 days', 
     'Equipe Technique USF-ADC', 
     15, 
     'Dakar, Sénégal', 
     'published', 
     'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&auto=format&fit=crop&q=60')
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    type = EXCLUDED.type,
    start_date = EXCLUDED.start_date,
    end_date = EXCLUDED.end_date,
    trainer = EXCLUDED.trainer,
    capacity = EXCLUDED.capacity,
    location = EXCLUDED.location,
    status = EXCLUDED.status,
    image_url = EXCLUDED.image_url;
